### ISSUE TITLE
Different Intervention Locations on Different Model Components

### ISSUE THREAD

**Issue by comeandcode** [stanfordnlp/pyreft#117]
Hi, I am wondering if it is possible to intervene a model which contains both some layers of encoders and some layers of decoders. And I would like to assign different intervention locations for these two kinds of transformer blocks. I found that in the pyvene library, it just supports one intervention_locations argument. If it is possible to realize things like only prefix (7) for encoders and f7+l7 for decoders without modifying the original library? Thank you!

**Comment by PinetreePantry** [comment]
It is definitely possible to do this. See [this section that creates interventions to different parts of the code](https://github.com/stanfordnlp/pyreft/blob/97768c053c3bbb05194ffef00f523ca9952c9a2c/examples/loreft/train.py#L317-L338). Beware that you also need to [modify the intervention locations in the dataset file](https://github.com/stanfordnlp/pyreft/blob/97768c053c3bbb05194ffef00f523ca9952c9a2c/pyreft/dataset.py#L67-L109) so that the intervention locations match the interventions.

Also note, decoder interventions are harder to implement correctly. You need to intervene on a variety length of input IDs, which complicates collating and padding. But theoretically there is nothing that prevents implementing encoder-decoder interventions. Pyvene/Pyreft is just a model intervening library that can do anything. Checkout my [PR](https://github.com/stanfordnlp/pyreft/pull/119) for an example.

**Comment by comeandcode** [comment]
Thank you for your reply! I will try it!
